global:
  scrape_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "sit223-flask-app"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:5000"